-- Nationwide Script to fix ward-constituency mappings
-- Generated based on comprehensive CSV data

UPDATE kenya_wards SET constituency = 'Baringo  North' WHERE county = 'Baringo' AND ward IN ('Bartabwa', 'Barwessa', 'Kabartonjo', 'Saimo/Kipsaraman', 'Saimo/Soi');
UPDATE kenya_wards SET constituency = 'Baringo Central' WHERE county = 'Baringo' AND ward IN ('Ewalel Chapchap', 'Kabarnet', 'Kapropita', 'Sacho', 'Tenges');
UPDATE kenya_wards SET constituency = 'Baringo South' WHERE county = 'Baringo' AND ward IN ('Ilchamus', 'Marigat', 'Mochongoi', 'Mukutani');
UPDATE kenya_wards SET constituency = 'Eldama Ravine' WHERE county = 'Baringo' AND ward IN ('Koibatek', 'Lembus', 'Lembus Kwen', 'Lembus/Perkerra', 'Mumberes/Maji Mazuri', 'Ravine');
UPDATE kenya_wards SET constituency = 'Mogotio' WHERE county = 'Baringo' AND ward IN ('Emining', 'Kisanana', 'Mogotio');
UPDATE kenya_wards SET constituency = 'Tiaty' WHERE county = 'Baringo' AND ward IN ('Churo/Amaya', 'Kolowa', 'Loiyamorock', 'Ribkwo', 'Silale', 'Tangulbei/Korossi', 'Tirioko');
UPDATE kenya_wards SET constituency = 'Bomet Central' WHERE county = 'Bomet' AND ward IN ('Chesoen', 'Mutarakwa', 'Ndaraweta', 'Silibwet Township', 'Singorwet');
UPDATE kenya_wards SET constituency = 'Bomet East' WHERE county = 'Bomet' AND ward IN ('Chemaner', 'Kembu', 'Kipreres', 'Longisa', 'Merigi');
UPDATE kenya_wards SET constituency = 'Chepalungu' WHERE county = 'Bomet' AND ward IN ('Chebunyo', 'Kong''Asis', 'Nyangores', 'Sigor', 'Siongiroi');
UPDATE kenya_wards SET constituency = 'Konoin' WHERE county = 'Bomet' AND ward IN ('Boito', 'Chepchabas', 'Embomos', 'Kimulot', 'Mogogosiek');
UPDATE kenya_wards SET constituency = 'Sotik' WHERE county = 'Bomet' AND ward IN ('Chemagel', 'Kapletundo', 'Kipsonoi', 'Ndanai/Abosi', 'Rongena/Manaret');
UPDATE kenya_wards SET constituency = 'Bumula' WHERE county = 'Bungoma' AND ward IN ('Bumula', 'Kabula', 'Khasoko', 'Kimaeti', 'Siboti', 'South Bukusu', 'West Bukusu');
UPDATE kenya_wards SET constituency = 'Kabuchai' WHERE county = 'Bungoma' AND ward IN ('Bwake/Luuya', 'Kabuchai/Chwele', 'Mukuyuni', 'West Nalondo');
UPDATE kenya_wards SET constituency = 'Kanduyi' WHERE county = 'Bungoma' AND ward IN ('Bukembe East', 'Bukembe West', 'East Sang''Alo', 'Khalaba', 'Marakaru/Tuuti', 'Musikoma', 'Sang''Alo West', 'Township');
UPDATE kenya_wards SET constituency = 'Kimilili' WHERE county = 'Bungoma' AND ward IN ('Kamukuywa', 'Kibingei', 'Kimilili', 'Maeni');
UPDATE kenya_wards SET constituency = 'Mt.Elgon' WHERE county = 'Bungoma' AND ward IN ('Cheptais', 'Chepyuk', 'Chesikaki', 'Elgon', 'Kapkateny', 'Kaptama');
UPDATE kenya_wards SET constituency = 'Sirisia' WHERE county = 'Bungoma' AND ward IN ('Lwandanyi', 'Malakisi/South Kulisiru', 'Namwela');
UPDATE kenya_wards SET constituency = 'Tongaren' WHERE county = 'Bungoma' AND ward IN ('Mbakalo', 'Milima', 'Naitiri/Kabuyefwe', 'Ndalu/ Tabani', 'Soysambu/ Mitua', 'Tongaren');
UPDATE kenya_wards SET constituency = 'Webuye East' WHERE county = 'Bungoma' AND ward IN ('Maraka', 'Mihuu', 'Ndivisi');
UPDATE kenya_wards SET constituency = 'Webuye West' WHERE county = 'Bungoma' AND ward IN ('Bokoli', 'Matulo', 'Misikhu', 'Sitikho');
UPDATE kenya_wards SET constituency = 'Budalangi' WHERE county = 'Busia' AND ward IN ('Bunyala Central', 'Bunyala North', 'Bunyala South', 'Bunyala West');
UPDATE kenya_wards SET constituency = 'Butula' WHERE county = 'Busia' AND ward IN ('Elugulu', 'Kingandole', 'Marachi Central', 'Marachi East', 'Marachi North', 'Marachi West');
UPDATE kenya_wards SET constituency = 'Funyula' WHERE county = 'Busia' AND ward IN ('Ageng''A Nanguba', 'Bwiri', 'Namboboto Nambuku', 'Nangina');
UPDATE kenya_wards SET constituency = 'Matayos' WHERE county = 'Busia' AND ward IN ('Bukhayo West', 'Burumba', 'Busibwabo', 'Matayos South', 'Mayenje');
UPDATE kenya_wards SET constituency = 'Nambale' WHERE county = 'Busia' AND ward IN ('Bukhayo Central', 'Bukhayo East', 'Bukhayo North/Waltsi', 'Nambale Township');
UPDATE kenya_wards SET constituency = 'Teso North' WHERE county = 'Busia' AND ward IN ('Ang''Urai East', 'Ang''Urai North', 'Ang''Urai South', 'Malaba Central', 'Malaba North', 'Malaba South');
UPDATE kenya_wards SET constituency = 'Teso South' WHERE county = 'Busia' AND ward IN ('Amukura Central', 'Amukura East', 'Amukura West', 'Ang''Orom', 'Chakol North', 'Chakol South');
UPDATE kenya_wards SET constituency = 'Keiyo North' WHERE county = 'Elgeyo/Marakwet' AND ward IN ('Emsoo', 'Kamariny', 'Kapchemutwa', 'Tambach');
UPDATE kenya_wards SET constituency = 'Keiyo South' WHERE county = 'Elgeyo/Marakwet' AND ward IN ('Chepkorio', 'Kabiemit', 'Kaptarakwa', 'Metkei', 'Soy North', 'Soy South');
UPDATE kenya_wards SET constituency = 'Marakwet East' WHERE county = 'Elgeyo/Marakwet' AND ward IN ('Embobut / Embulot', 'Endo', 'Kapyego', 'Sambirir');
UPDATE kenya_wards SET constituency = 'Marakwet West' WHERE county = 'Elgeyo/Marakwet' AND ward IN ('Arror', 'Cherang''Any/Chebororwa', 'Kapsowar', 'Lelan', 'Moiben/Kuserwo', 'Sengwer');
UPDATE kenya_wards SET constituency = 'Manyatta' WHERE county = 'Embu' AND ward IN ('Gaturi South', 'Kirimari', 'Kithimu', 'Mbeti North', 'Nginda', 'Ruguru/Ngandori');
UPDATE kenya_wards SET constituency = 'Mbeere North' WHERE county = 'Embu' AND ward IN ('Evurore', 'Muminji', 'Nthawa');
UPDATE kenya_wards SET constituency = 'Mbeere South' WHERE county = 'Embu' AND ward IN ('Kiambere', 'Makima', 'Mavuria', 'Mbeti South', 'Mwea');
UPDATE kenya_wards SET constituency = 'Runyenjes' WHERE county = 'Embu' AND ward IN ('Central  Ward', 'Gaturi North', 'Kagaari North', 'Kagaari South', 'Kyeni North', 'Kyeni South');
UPDATE kenya_wards SET constituency = 'Balambala' WHERE county = 'Garissa' AND ward IN ('Balambala', 'Danyere', 'Jara Jara', 'Saka', 'Sankuri');
UPDATE kenya_wards SET constituency = 'Dadaab' WHERE county = 'Garissa' AND ward IN ('Abakaile', 'Dadaab', 'Damajale', 'Dertu', 'Labasigale', 'Liboi');
UPDATE kenya_wards SET constituency = 'Fafi' WHERE county = 'Garissa' AND ward IN ('Bura', 'Dekaharia', 'Fafi', 'Jarajila', 'Nanighi');
UPDATE kenya_wards SET constituency = 'Garissa Township' WHERE county = 'Garissa' AND ward IN ('Galbet', 'Iftin', 'Township', 'Waberi');
UPDATE kenya_wards SET constituency = 'Ijara' WHERE county = 'Garissa' AND ward IN ('Hulugho', 'Ijara', 'Masalani', 'Sangailu');
UPDATE kenya_wards SET constituency = 'Lagdera' WHERE county = 'Garissa' AND ward IN ('Baraki', 'Benane', 'Goreale', 'Maalimin', 'Modogashe', 'Sabena');
UPDATE kenya_wards SET constituency = 'Homa Bay Town' WHERE county = 'Homa Bay' AND ward IN ('Homa Bay Arujo', 'Homa Bay Central', 'Homa Bay East', 'Homa Bay West');
UPDATE kenya_wards SET constituency = 'Kabondo Kasipul' WHERE county = 'Homa Bay' AND ward IN ('Kabondo East', 'Kabondo West', 'Kojwach', 'Kokwanyo/Kakelo');
UPDATE kenya_wards SET constituency = 'Karachuonyo' WHERE county = 'Homa Bay' AND ward IN ('Central', 'Kanyaluo', 'Kendu Bay Town', 'Kibiri', 'North Karachuonyo', 'Wangchieng', 'West Karachuonyo');
UPDATE kenya_wards SET constituency = 'Kasipul' WHERE county = 'Homa Bay' AND ward IN ('Central Kasipul', 'East Kamagak', 'South Kasipul', 'West Kamagak', 'West Kasipul');
UPDATE kenya_wards SET constituency = 'Mbita' WHERE county = 'Homa Bay' AND ward IN ('Gembe', 'Kasgunga', 'Lambwe', 'Mfangano Island', 'Rusinga Island');
UPDATE kenya_wards SET constituency = 'Ndhiwa' WHERE county = 'Homa Bay' AND ward IN ('Kabuoch South/Pala', 'Kanyadoto', 'Kanyamwa Kologi', 'Kanyamwa Kosewe', 'Kanyikela', 'Kwabwai', 'North Kabuoch');
UPDATE kenya_wards SET constituency = 'Rangwe' WHERE county = 'Homa Bay' AND ward IN ('East Gem', 'Kagan', 'Kochia', 'West Gem');
UPDATE kenya_wards SET constituency = 'Suba' WHERE county = 'Homa Bay' AND ward IN ('Gwassi North', 'Gwassi South', 'Kaksingri West', 'Ruma Kaksingri East');
UPDATE kenya_wards SET constituency = 'Isiolo North' WHERE county = 'Isiolo' AND ward IN ('Bulla Pesa', 'Burat', 'Chari', 'Cherab', 'Ngare Mara', 'Oldonyiro', 'Wabera');
UPDATE kenya_wards SET constituency = 'Isiolo South' WHERE county = 'Isiolo' AND ward IN ('Garbatulla', 'Kinna', 'Sericho');
UPDATE kenya_wards SET constituency = 'Kajiado Central' WHERE county = 'Kajiado' AND ward IN ('Dalalekutuk', 'Ildamat', 'Matapato North', 'Matapato South', 'Purko');
UPDATE kenya_wards SET constituency = 'Kajiado East' WHERE county = 'Kajiado' AND ward IN ('Imaroro', 'Kaputiei North', 'Kenyawa-Poka', 'Kitengela', 'Oloosirkon/Sholinke');
UPDATE kenya_wards SET constituency = 'Kajiado North' WHERE county = 'Kajiado' AND ward IN ('Ngong', 'Nkaimurunya', 'Olkeri', 'Oloolua', 'Ongata Rongai');
UPDATE kenya_wards SET constituency = 'Kajiado South' WHERE county = 'Kajiado' AND ward IN ('Entonet/Lenkisim', 'Kimana', 'Kuku', 'Mbirikani/Eselenkei', 'Rombo');
UPDATE kenya_wards SET constituency = 'Kajiado West' WHERE county = 'Kajiado' AND ward IN ('Ewuaso Oonkidong''I', 'Iloodokilani', 'Keekonyokie', 'Magadi', 'Mosiro');
UPDATE kenya_wards SET constituency = 'Butere' WHERE county = 'Kakamega' AND ward IN ('Marama Central', 'Marama North', 'Marama South', 'Marama West', 'Marenyo - Shianda');
UPDATE kenya_wards SET constituency = 'Ikolomani' WHERE county = 'Kakamega' AND ward IN ('Idakho Central', 'Idakho East', 'Idakho North', 'Idakho South');
UPDATE kenya_wards SET constituency = 'Khwisero' WHERE county = 'Kakamega' AND ward IN ('Kisa Central', 'Kisa East', 'Kisa North', 'Kisa West');
UPDATE kenya_wards SET constituency = 'Likuyani' WHERE county = 'Kakamega' AND ward IN ('Kongoni', 'Likuyani', 'Nzoia', 'Sango', 'Sinoko');
UPDATE kenya_wards SET constituency = 'Lugari' WHERE county = 'Kakamega' AND ward IN ('Chekalini', 'Chevaywa', 'Lugari', 'Lumakanda', 'Lwandeti', 'Mautuma');
UPDATE kenya_wards SET constituency = 'Lurambi' WHERE county = 'Kakamega' AND ward IN ('Butsotso Central', 'Butsotso East', 'Butsotso South', 'Mahiakalo', 'Sheywe', 'Shirere');
UPDATE kenya_wards SET constituency = 'Malava' WHERE county = 'Kakamega' AND ward IN ('Butali/Chegulo', 'Chemuche', 'East Kabras', 'Manda-Shivanga', 'Shirugu-Mugai', 'South Kabras', 'West Kabras');
UPDATE kenya_wards SET constituency = 'Matungu' WHERE county = 'Kakamega' AND ward IN ('Khalaba', 'Kholera', 'Koyonzo', 'Mayoni', 'Namamali');
UPDATE kenya_wards SET constituency = 'Mumias East' WHERE county = 'Kakamega' AND ward IN ('East Wanga', 'Isongo/Makunga/Malaha', 'Lubinu/Lusheya');
UPDATE kenya_wards SET constituency = 'Mumias West' WHERE county = 'Kakamega' AND ward IN ('Etenje', 'Mumias Central', 'Mumias North', 'Musanda');
UPDATE kenya_wards SET constituency = 'Navakholo' WHERE county = 'Kakamega' AND ward IN ('Bunyala Central', 'Bunyala East', 'Bunyala West', 'Ingostse-Mathia', 'Shinoyi-Shikomari-');
UPDATE kenya_wards SET constituency = 'Shinyalu' WHERE county = 'Kakamega' AND ward IN ('Isukha Central', 'Isukha East', 'Isukha North', 'Isukha South', 'Isukha West', 'Murhanda');
UPDATE kenya_wards SET constituency = 'Ainamoi' WHERE county = 'Kericho' AND ward IN ('Ainamoi', 'Kapkugerwet', 'Kapsaos', 'Kapsoit', 'Kipchebor', 'Kipchimchim');
UPDATE kenya_wards SET constituency = 'Belgut' WHERE county = 'Kericho' AND ward IN ('Chaik', 'Cheptororiet/Seretut', 'Kabianga', 'Kapsuser', 'Waldai');
UPDATE kenya_wards SET constituency = 'Bureti' WHERE county = 'Kericho' AND ward IN ('Cheboin', 'Chemosot', 'Cheplanget', 'Kapkatet', 'Kisiara', 'Litein', 'Tebesonik');
UPDATE kenya_wards SET constituency = 'Kipkelion East' WHERE county = 'Kericho' AND ward IN ('Chepseon', 'Kedowa/Kimugul', 'Londiani', 'Tendeno/Sorget');
UPDATE kenya_wards SET constituency = 'Kipkelion West' WHERE county = 'Kericho' AND ward IN ('Chilchila', 'Kamasian', 'Kipkelion', 'Kunyak');
UPDATE kenya_wards SET constituency = 'Sigowet/Soin' WHERE county = 'Kericho' AND ward IN ('Kaplelartet', 'Sigowet', 'Soin', 'Soliat');
UPDATE kenya_wards SET constituency = 'Gatundu North' WHERE county = 'Kiambu' AND ward IN ('Chania', 'Githobokoni', 'Gituamba', 'Mang''U');
UPDATE kenya_wards SET constituency = 'Gatundu South' WHERE county = 'Kiambu' AND ward IN ('Kiamwangi', 'Kiganjo', 'Ndarugu', 'Ngenda');
UPDATE kenya_wards SET constituency = 'Githunguri' WHERE county = 'Kiambu' AND ward IN ('Githiga', 'Githunguri', 'Ikinu', 'Komothai', 'Ngewa');
UPDATE kenya_wards SET constituency = 'Juja' WHERE county = 'Kiambu' AND ward IN ('Juja', 'Kalimoni', 'Murera', 'Theta', 'Witeithie');
UPDATE kenya_wards SET constituency = 'Kabete' WHERE county = 'Kiambu' AND ward IN ('Gitaru', 'Kabete', 'Muguga', 'Nyadhuna', 'Uthiru');
UPDATE kenya_wards SET constituency = 'Kiambaa' WHERE county = 'Kiambu' AND ward IN ('Cianda', 'Karuri', 'Kihara', 'Muchatha', 'Ndenderu');
UPDATE kenya_wards SET constituency = 'Kiambu' WHERE county = 'Kiambu' AND ward IN ('Ndumberi', 'Riabai', 'Ting''Ang''A', 'Township');
UPDATE kenya_wards SET constituency = 'Kikuyu' WHERE county = 'Kiambu' AND ward IN ('Karai', 'Kikuyu', 'Kinoo', 'Nachu', 'Sigona');
UPDATE kenya_wards SET constituency = 'Lari' WHERE county = 'Kiambu' AND ward IN ('Kamburu', 'Kijabe', 'Kinale', 'Lari/Kirenga', 'Nyanduma');
UPDATE kenya_wards SET constituency = 'Limuru' WHERE county = 'Kiambu' AND ward IN ('Bibirioni', 'Limuru Central', 'Limuru East', 'Ndeiya', 'Ngecha Tigoni');
UPDATE kenya_wards SET constituency = 'Ruiru' WHERE county = 'Kiambu' AND ward IN ('Biashara', 'Gatongora', 'Gitothua', 'Kahawa Sukari', 'Kahawa Wendani', 'Kiuu', 'Mwihoko', 'Mwiki');
UPDATE kenya_wards SET constituency = 'Thika Town' WHERE county = 'Kiambu' AND ward IN ('Gatuanyaga', 'Hospital', 'Kamenu', 'Ngoliba');
UPDATE kenya_wards SET constituency = 'Ganze' WHERE county = 'Kilifi' AND ward IN ('Bamba', 'Ganze', 'Jaribuni', 'Sokoke');
UPDATE kenya_wards SET constituency = 'Kaloleni' WHERE county = 'Kilifi' AND ward IN ('Kaloleni', 'Kayafungo', 'Mariakani', 'Mwanamwinga');
UPDATE kenya_wards SET constituency = 'Kilifi North' WHERE county = 'Kilifi' AND ward IN ('Dabaso', 'Kibarani', 'Matsangoni', 'Mnarani', 'Sokoni', 'Tezo', 'Watamu');
UPDATE kenya_wards SET constituency = 'Kilifi South' WHERE county = 'Kilifi' AND ward IN ('Chasimba', 'Junju', 'Mtepeni', 'Mwarakaya', 'Shimo La Tewa');
UPDATE kenya_wards SET constituency = 'Magarini' WHERE county = 'Kilifi' AND ward IN ('Adu', 'Garashi', 'Gongoni', 'Magarini', 'Marafa', 'Sabaki');
UPDATE kenya_wards SET constituency = 'Malindi' WHERE county = 'Kilifi' AND ward IN ('Ganda', 'Jilore', 'Kakuyuni', 'Malindi Town', 'Shella');
UPDATE kenya_wards SET constituency = 'Rabai' WHERE county = 'Kilifi' AND ward IN ('Kambe/Ribe', 'Mwawesa', 'Rabai/Kisurutini', 'Ruruma');
UPDATE kenya_wards SET constituency = 'Gichugu' WHERE county = 'Kirinyaga' AND ward IN ('Baragwi', 'Kabare', 'Karumandi', 'Ngariama', 'Njukiini');
UPDATE kenya_wards SET constituency = 'Kirinyaga Central' WHERE county = 'Kirinyaga' AND ward IN ('Inoi', 'Kanyeki-Ini', 'Kerugoya', 'Mutira');
UPDATE kenya_wards SET constituency = 'Mwea' WHERE county = 'Kirinyaga' AND ward IN ('Gathigiriri', 'Kangai', 'Murinduko', 'Mutithi', 'Nyangati', 'Tebere', 'Thiba', 'Wamumu');
UPDATE kenya_wards SET constituency = 'Ndia' WHERE county = 'Kirinyaga' AND ward IN ('Kariti', 'Kiine', 'Mukure');
UPDATE kenya_wards SET constituency = 'Bobasi' WHERE county = 'Kisii' AND ward IN ('Bobasi Bogetaorio', 'Bobasi Boitangare', 'Bobasi Central', 'Bobasi Chache', 'Masige East', 'Masige West', 'Nyacheki', 'Sameta/Mokwerero');
UPDATE kenya_wards SET constituency = 'Bomachoge Borabu' WHERE county = 'Kisii' AND ward IN ('Bokimonge', 'Bombaba Borabu', 'Boochi Borabu', 'Magenche');
UPDATE kenya_wards SET constituency = 'Bomachoge Chache' WHERE county = 'Kisii' AND ward IN ('Boochi/Tendere', 'Bosoti/Sengera', 'Majoge');
UPDATE kenya_wards SET constituency = 'Bonchari' WHERE county = 'Kisii' AND ward IN ('Bogiakumu', 'Bomariba', 'Bomorenda', 'Riana');
UPDATE kenya_wards SET constituency = 'Kitutu Chache North' WHERE county = 'Kisii' AND ward IN ('Kegogi', 'Marani', 'Monyerero', 'Sensi');
UPDATE kenya_wards SET constituency = 'Kitutu Chache South' WHERE county = 'Kisii' AND ward IN ('Bogeka', 'Bogusero', 'Kitutu   Central', 'Nyakoe', 'Nyatieko');
UPDATE kenya_wards SET constituency = 'Nyaribari Chache' WHERE county = 'Kisii' AND ward IN ('Birongo', 'Bobaracho', 'Ibeno', 'Keumbu', 'Kiogoro', 'Kisii Central');
UPDATE kenya_wards SET constituency = 'Nyaribari Masaba' WHERE county = 'Kisii' AND ward IN ('Gesusu', 'Ichuni', 'Kiamokama', 'Masimba', 'Nyamasibi');
UPDATE kenya_wards SET constituency = 'South Mugirango' WHERE county = 'Kisii' AND ward IN ('Bogetenga', 'Boikang''A', 'Borabu / Chitago', 'Getenga', 'Moticho', 'Tabaka');
UPDATE kenya_wards SET constituency = 'Kisumu Central' WHERE county = 'Kisumu' AND ward IN ('Kondele', 'Market Milimani', 'Migosi', 'Nyalenda B', 'Railways', 'Shaurimoyo Kaloleni');
UPDATE kenya_wards SET constituency = 'Kisumu East' WHERE county = 'Kisumu' AND ward IN ('Kajulu', 'Kolwa Central', 'Kolwa East', 'Manyatta ''B''', 'Nyalenda ''A''');
UPDATE kenya_wards SET constituency = 'Kisumu West' WHERE county = 'Kisumu' AND ward IN ('Central Kisumu', 'Kisumu North', 'North West Kisumu', 'South West Kisumu', 'West Kisumu');
UPDATE kenya_wards SET constituency = 'Muhoroni' WHERE county = 'Kisumu' AND ward IN ('Chemelil', 'Masogo/Nyang''Oma', 'Miwani', 'Muhoroni/Koru', 'Ombeyi');
UPDATE kenya_wards SET constituency = 'Nyakach' WHERE county = 'Kisumu' AND ward IN ('Central Nyakach', 'North Nyakach', 'South East Nyakach', 'South West Nyakach', 'West Nyakach');
UPDATE kenya_wards SET constituency = 'Nyando' WHERE county = 'Kisumu' AND ward IN ('Ahero', 'Awasi/Onjiko', 'East Kano/Wawidhi', 'Kabonyo/Kanyagwal', 'Kobura');
UPDATE kenya_wards SET constituency = 'Seme' WHERE county = 'Kisumu' AND ward IN ('Central Seme', 'East Seme', 'North Seme', 'West Seme');
UPDATE kenya_wards SET constituency = 'Kitui Central' WHERE county = 'Kitui' AND ward IN ('Kyangwithya East', 'Kyangwithya West', 'Miambani', 'Mulango', 'Township');
UPDATE kenya_wards SET constituency = 'Kitui East' WHERE county = 'Kitui' AND ward IN ('Chuluni', 'Endau/Malalani', 'Mutito/Kaliku', 'Nzambani', 'Voo/Kyamatu', 'Zombe/Mwitika');
UPDATE kenya_wards SET constituency = 'Kitui Rural' WHERE county = 'Kitui' AND ward IN ('Kanyangi', 'Kisasi', 'Kwavonza/Yatta', 'Mbitini');
UPDATE kenya_wards SET constituency = 'Kitui South' WHERE county = 'Kitui' AND ward IN ('Athi', 'Ikanga/Kyatune', 'Ikutha', 'Kanziko', 'Mutha', 'Mutomo');
UPDATE kenya_wards SET constituency = 'Kitui West' WHERE county = 'Kitui' AND ward IN ('Kauwi', 'Kwa Mutonga/Kithumula', 'Matinyani', 'Mutonguni');
UPDATE kenya_wards SET constituency = 'Mwingi Central' WHERE county = 'Kitui' AND ward IN ('Central', 'Kivou', 'Mui', 'Nguni', 'Nuu', 'Waita');
UPDATE kenya_wards SET constituency = 'Mwingi North' WHERE county = 'Kitui' AND ward IN ('Kyuso', 'Mumoni', 'Ngomeni', 'Tharaka', 'Tseikuru');
UPDATE kenya_wards SET constituency = 'Mwingi West' WHERE county = 'Kitui' AND ward IN ('Kiomo/Kyethani', 'Kyome/Thaana', 'Migwani', 'Nguutani');
UPDATE kenya_wards SET constituency = 'Kinango' WHERE county = 'Kwale' AND ward IN ('Chengoni/Samburu', 'Kasemeni', 'Kinango', 'Mackinnon-Road', 'Mwavumbo', 'Nadavaya', 'Puma');
UPDATE kenya_wards SET constituency = 'Lungalunga' WHERE county = 'Kwale' AND ward IN ('Dzombo', 'Mwereni', 'Pongwekikoneni', 'Vanga');
UPDATE kenya_wards SET constituency = 'Matuga' WHERE county = 'Kwale' AND ward IN ('Kubo South', 'Mkongani', 'Tiwi', 'Tsimba Golini', 'Waa');
UPDATE kenya_wards SET constituency = 'Msambweni' WHERE county = 'Kwale' AND ward IN ('Gombatobongwe', 'Kinondo', 'Ramisi', 'Ukunda');
UPDATE kenya_wards SET constituency = 'Laikipia East' WHERE county = 'Laikipia' AND ward IN ('Nanyuki', 'Ngobit', 'Thingithu', 'Tigithi', 'Umande');
UPDATE kenya_wards SET constituency = 'Laikipia North' WHERE county = 'Laikipia' AND ward IN ('Mukogondo East', 'Mukogondo West', 'Segera', 'Sosian');
UPDATE kenya_wards SET constituency = 'Laikipia West' WHERE county = 'Laikipia' AND ward IN ('Igwamiti', 'Kinamba', 'Marmanet', 'Olmoran', 'Rumuruti Township', 'Salama');
UPDATE kenya_wards SET constituency = 'Lamu East' WHERE county = 'Lamu' AND ward IN ('Basuba', 'Faza', 'Kiunga');
UPDATE kenya_wards SET constituency = 'Lamu West' WHERE county = 'Lamu' AND ward IN ('Bahari', 'Hindi', 'Hongwe', 'Mkomani', 'Mkunumbi', 'Shella', 'Witu');
UPDATE kenya_wards SET constituency = 'Kangundo' WHERE county = 'Machakos' AND ward IN ('Kangundo Central', 'Kangundo East', 'Kangundo North', 'Kangundo West');
UPDATE kenya_wards SET constituency = 'Kathiani' WHERE county = 'Machakos' AND ward IN ('Kathiani Central', 'Lower Kaewa/Kaani', 'Mitaboni', 'Upper Kaewa/Iveti');
UPDATE kenya_wards SET constituency = 'Machakos Town' WHERE county = 'Machakos' AND ward IN ('Kalama', 'Kola', 'Machakos Central', 'Mua', 'Mumbuni North', 'Mutituni', 'Muvuti/Kiima-Kimwe');
UPDATE kenya_wards SET constituency = 'Masinga' WHERE county = 'Machakos' AND ward IN ('Ekalakala', 'Kivaa', 'Masinga Central', 'Muthesya', 'Ndithini');
UPDATE kenya_wards SET constituency = 'Matungulu' WHERE county = 'Machakos' AND ward IN ('Kyeleni', 'Matungulu East', 'Matungulu North', 'Matungulu West', 'Tala');
UPDATE kenya_wards SET constituency = 'Mavoko' WHERE county = 'Machakos' AND ward IN ('Athi River', 'Kinanie', 'Muthwani', 'Syokimau/Mulolongo');
UPDATE kenya_wards SET constituency = 'Mwala' WHERE county = 'Machakos' AND ward IN ('Kibauni', 'Makutano/ Mwala', 'Masii', 'Mbiuni', 'Muthetheni', 'Wamunyu');
UPDATE kenya_wards SET constituency = 'Yatta' WHERE county = 'Machakos' AND ward IN ('Ikombe', 'Katangi', 'Kithimani', 'Matuu', 'Ndalani');
UPDATE kenya_wards SET constituency = 'Kaiti' WHERE county = 'Makueni' AND ward IN ('Ilima', 'Kee', 'Kilungu', 'Ukia');
UPDATE kenya_wards SET constituency = 'Kibwezi East' WHERE county = 'Makueni' AND ward IN ('Ivingoni/Nzambani', 'Masongaleni', 'Mtito Andei', 'Thange');
UPDATE kenya_wards SET constituency = 'Kibwezi West' WHERE county = 'Makueni' AND ward IN ('Emali/Mulala', 'Kikumbulyu North', 'Kikumbulyu South', 'Makindu', 'Nguu/Masumba', 'Nguumo');
UPDATE kenya_wards SET constituency = 'Kilome' WHERE county = 'Makueni' AND ward IN ('Kasikeu', 'Kiima Kiu/Kalanzoni', 'Mukaa');
UPDATE kenya_wards SET constituency = 'Makueni' WHERE county = 'Makueni' AND ward IN ('Kathonzweni', 'Kitise/Kithuki', 'Mavindini', 'Mbitini', 'Muvau/Kikuumini', 'Nzaui/Kilili/Kalamba', 'Wote');
UPDATE kenya_wards SET constituency = 'Mbooni' WHERE county = 'Makueni' AND ward IN ('Kalawa', 'Kisau/Kiteta', 'Kithungo/Kitundu', 'Mbooni', 'Tulimani', 'Waia/Kako');
UPDATE kenya_wards SET constituency = 'Banissa' WHERE county = 'Mandera' AND ward IN ('Banissa', 'Derkhale', 'Guba', 'Kiliwehiri', 'Malkamari');
UPDATE kenya_wards SET constituency = 'Lafey' WHERE county = 'Mandera' AND ward IN ('Alungo Gof', 'Fino', 'Lafey', 'Libehia', 'Warankara');
UPDATE kenya_wards SET constituency = 'Mandera East' WHERE county = 'Mandera' AND ward IN ('Arabia', 'Bulla Mpya', 'Khalalio', 'Neboi', 'Township');
UPDATE kenya_wards SET constituency = 'Mandera North' WHERE county = 'Mandera' AND ward IN ('Ashabito', 'Guticha', 'Morothile', 'Rhamu', 'Rhamu-Dimtu');
UPDATE kenya_wards SET constituency = 'Mandera South' WHERE county = 'Mandera' AND ward IN ('Elwak North', 'Elwak South', 'Kutulo', 'Shimbir Fatuma', 'Wargudud');
UPDATE kenya_wards SET constituency = 'Mandera West' WHERE county = 'Mandera' AND ward IN ('Dandu', 'Gither', 'Lag Sure', 'Takaba', 'Takaba South');
UPDATE kenya_wards SET constituency = 'Laisamis' WHERE county = 'Marsabit' AND ward IN ('Kargi/South Horr', 'Korr/Ngurunit', 'Laisamis', 'Log Logo', 'Loiyangalani');
UPDATE kenya_wards SET constituency = 'Moyale' WHERE county = 'Marsabit' AND ward IN ('Butiye', 'Golbo', 'Heilu-Manyatta', 'Moyale Township', 'Obbu', 'Sololo', 'Uran');
UPDATE kenya_wards SET constituency = 'North Horr' WHERE county = 'Marsabit' AND ward IN ('Dukana', 'Illeret', 'Maikona', 'North Horr', 'Turbi');
UPDATE kenya_wards SET constituency = 'Saku' WHERE county = 'Marsabit' AND ward IN ('Karare', 'Marsabit Central', 'Sagante/Jaldesa');
UPDATE kenya_wards SET constituency = 'Buuri' WHERE county = 'Meru' AND ward IN ('Kibirichia', 'Kiirua/Naari', 'Kisima', 'Ruiri/Rwarera', 'Timau');
UPDATE kenya_wards SET constituency = 'Central Imenti' WHERE county = 'Meru' AND ward IN ('Abothuguchi Central', 'Abothuguchi West', 'Kiagu', 'Mwanganthia');
UPDATE kenya_wards SET constituency = 'Igembe Central' WHERE county = 'Meru' AND ward IN ('Akirang''Ondu', 'Athiru Ruujine', 'Igembe East', 'Kangeta', 'Njia');
UPDATE kenya_wards SET constituency = 'Igembe North' WHERE county = 'Meru' AND ward IN ('Amwathi', 'Antuambui', 'Antubetwe Kiongo', 'Naathu', 'Ntunene');
UPDATE kenya_wards SET constituency = 'Igembe South' WHERE county = 'Meru' AND ward IN ('Akachiu', 'Athiru Gaiti', 'Kanuni', 'Kiegoi/Antubochiu', 'Maua');
UPDATE kenya_wards SET constituency = 'North Imenti' WHERE county = 'Meru' AND ward IN ('Municipality', 'Ntima East', 'Ntima West', 'Nyaki East', 'Nyaki West');
UPDATE kenya_wards SET constituency = 'South Imenti' WHERE county = 'Meru' AND ward IN ('Abogeta East', 'Abogeta West', 'Igoji East', 'Igoji West', 'Mitunguu', 'Nkuene');
UPDATE kenya_wards SET constituency = 'Tigania East' WHERE county = 'Meru' AND ward IN ('Karama', 'Kiguchwa', 'Mikinduri', 'Muthara', 'Thangatha');
UPDATE kenya_wards SET constituency = 'Tigania West' WHERE county = 'Meru' AND ward IN ('Akithii', 'Athwana', 'Kianjai', 'Mbeu', 'Nkomo');
UPDATE kenya_wards SET constituency = 'Awendo' WHERE county = 'Migori' AND ward IN ('Central Sakwa', 'North Sakwa', 'South Sakwa', 'West Sakwa');
UPDATE kenya_wards SET constituency = 'Kuria East' WHERE county = 'Migori' AND ward IN ('Gokeharaka/Getambwega', 'Ntimaru East', 'Ntimaru West', 'Nyabasi East', 'Nyabasi West');
UPDATE kenya_wards SET constituency = 'Kuria West' WHERE county = 'Migori' AND ward IN ('Bukira Centrl/Ikerege', 'Bukira East', 'Isibania', 'Makerero', 'Masaba', 'Nyamosense/Komosoko', 'Tagare');
UPDATE kenya_wards SET constituency = 'Nyatike' WHERE county = 'Migori' AND ward IN ('Got Kachola', 'Kachien''G', 'Kaler', 'Kanyasa', 'Macalder/Kanyarwanda', 'Muhuru', 'North Kadem');
UPDATE kenya_wards SET constituency = 'Rongo' WHERE county = 'Migori' AND ward IN ('Central Kamagambo', 'East Kamagambo', 'North Kamagambo', 'South Kamagambo');
UPDATE kenya_wards SET constituency = 'Suna East' WHERE county = 'Migori' AND ward IN ('God Jope', 'Kakrao', 'Kwa', 'Suna Central');
UPDATE kenya_wards SET constituency = 'Suna West' WHERE county = 'Migori' AND ward IN ('Ragana-Oruba', 'Wasimbete', 'Wasweta Ii', 'Wiga');
UPDATE kenya_wards SET constituency = 'Uriri' WHERE county = 'Migori' AND ward IN ('Central Kanyamkago', 'East Kanyamkago', 'North Kanyamkago', 'South Kanyamkago', 'West Kanyamkago');
UPDATE kenya_wards SET constituency = 'Changamwe' WHERE county = 'Mombasa' AND ward IN ('Airport', 'Chaani', 'Changamwe', 'Kipevu', 'Port Reitz');
UPDATE kenya_wards SET constituency = 'Jomvu' WHERE county = 'Mombasa' AND ward IN ('Jomvu Kuu', 'Mikindani', 'Miritini');
UPDATE kenya_wards SET constituency = 'Kisauni' WHERE county = 'Mombasa' AND ward IN ('Bamburi', 'Junda', 'Magogoni', 'Mjambere', 'Mtopanga', 'Mwakirunge', 'Shanzu');
UPDATE kenya_wards SET constituency = 'Likoni' WHERE county = 'Mombasa' AND ward IN ('Bofu', 'Likoni', 'Mtongwe', 'Shika Adabu', 'Timbwani');
UPDATE kenya_wards SET constituency = 'Mvita' WHERE county = 'Mombasa' AND ward IN ('Majengo', 'Mji Wa Kale/Makadara', 'Shimanzi/Ganjoni', 'Tononoka', 'Tudor');
UPDATE kenya_wards SET constituency = 'Nyali' WHERE county = 'Mombasa' AND ward IN ('Frere Town', 'Kadzandani', 'Kongowea', 'Mkomani', 'Ziwa La Ng''Ombe');
UPDATE kenya_wards SET constituency = 'Gatanga' WHERE county = 'Murang''a' AND ward IN ('Gatanga', 'Ithanga', 'Kakuzi/Mitubiri', 'Kariara', 'Kihumbu-Ini', 'Mugumo-Ini');
UPDATE kenya_wards SET constituency = 'Kandara' WHERE county = 'Murang''a' AND ward IN ('Gaichanjiru', 'Ithiru', 'Kagundu-Ini', 'Muruka', 'Ng''Araria', 'Ruchu');
UPDATE kenya_wards SET constituency = 'Kangema' WHERE county = 'Murang''a' AND ward IN ('Kanyenyaini', 'Muguru', 'Rwathia');
UPDATE kenya_wards SET constituency = 'Kigumo' WHERE county = 'Murang''a' AND ward IN ('Kahumbu', 'Kangari', 'Kigumo', 'Kinyona', 'Muthithi');
UPDATE kenya_wards SET constituency = 'Kiharu' WHERE county = 'Murang''a' AND ward IN ('Gaturi', 'Mbiri', 'Mugoiri', 'Murarandia', 'Township', 'Wangu');
UPDATE kenya_wards SET constituency = 'Maragwa' WHERE county = 'Murang''a' AND ward IN ('Ichagaki', 'Kamahuha', 'Kambiti', 'Kimorori/Wempa', 'Makuyu', 'Nginda');
UPDATE kenya_wards SET constituency = 'Mathioya' WHERE county = 'Murang''a' AND ward IN ('Gitugi', 'Kamacharia', 'Kiru');
UPDATE kenya_wards SET constituency = 'Dagoretti North' WHERE county = 'Nairobi' AND ward IN ('Gatina', 'Kabiro', 'Kawangware', 'Kileleshwa', 'Kilimani');
UPDATE kenya_wards SET constituency = 'Dagoretti South' WHERE county = 'Nairobi' AND ward IN ('Mutuini', 'Ngando', 'Riruta', 'Uthiru/Ruthimitu', 'Waithaka');
UPDATE kenya_wards SET constituency = 'Embakasi Central' WHERE county = 'Nairobi' AND ward IN ('Kayole Central', 'Kayole North', 'Kayole South', 'Komarock', 'Matopeni');
UPDATE kenya_wards SET constituency = 'Embakasi East' WHERE county = 'Nairobi' AND ward IN ('Embakasi', 'Lower Savannah', 'Mihango', 'Upper Savannah', 'Utawala');
UPDATE kenya_wards SET constituency = 'Embakasi North' WHERE county = 'Nairobi' AND ward IN ('Dandora Area I', 'Dandora Area Ii', 'Dandora Area Iii', 'Dandora Area Iv', 'Kariobangi North');
UPDATE kenya_wards SET constituency = 'Embakasi South' WHERE county = 'Nairobi' AND ward IN ('Imara Daima', 'Kwa Njenga', 'Kwa Reuben', 'Kware', 'Pipeline');
UPDATE kenya_wards SET constituency = 'Embakasi West' WHERE county = 'Nairobi' AND ward IN ('Kariobangi South', 'Mowlem', 'Umoja I', 'Umoja Ii');
UPDATE kenya_wards SET constituency = 'Kamukunji' WHERE county = 'Nairobi' AND ward IN ('Airbase', 'California', 'Eastleigh North', 'Eastleigh South', 'Pumwani');
UPDATE kenya_wards SET constituency = 'Kasarani' WHERE county = 'Nairobi' AND ward IN ('Claycity', 'Kasarani', 'Mwiki', 'Njiru', 'Ruai');
UPDATE kenya_wards SET constituency = 'Kibra' WHERE county = 'Nairobi' AND ward IN ('Laini Saba', 'Lindi', 'Makina', 'Sarangombe', 'Woodley/Kenyatta Golf');
UPDATE kenya_wards SET constituency = 'Langata' WHERE county = 'Nairobi' AND ward IN ('Karen', 'Mugumo-Ini', 'Nairobi West', 'Nyayo Highrise', 'South-C');
UPDATE kenya_wards SET constituency = 'Makadara' WHERE county = 'Nairobi' AND ward IN ('Harambee', 'Makongeni', 'Maringo/Hamza', 'Viwandani');
UPDATE kenya_wards SET constituency = 'Mathare' WHERE county = 'Nairobi' AND ward IN ('Hospital', 'Huruma', 'Kiamaiko', 'Mabatini', 'Mlango Kubwa', 'Ngei');
UPDATE kenya_wards SET constituency = 'Roysambu' WHERE county = 'Nairobi' AND ward IN ('Githurai', 'Kahawa', 'Kahawa West', 'Roysambu', 'Zimmerman');
UPDATE kenya_wards SET constituency = 'Ruaraka' WHERE county = 'Nairobi' AND ward IN ('Baba Dogo', 'Korogocho', 'Lucky Summer', 'Mathare North', 'Utalii');
UPDATE kenya_wards SET constituency = 'Starehe' WHERE county = 'Nairobi' AND ward IN ('Landimawe', 'Nairobi Central', 'Nairobi South', 'Ngara', 'Pangani', 'Ziwani/Kariokor');
UPDATE kenya_wards SET constituency = 'Westlands' WHERE county = 'Nairobi' AND ward IN ('Kangemi', 'Karura', 'Kitisuru', 'Mountain View', 'Parklands/Highridge');
UPDATE kenya_wards SET constituency = 'Bahati' WHERE county = 'Nakuru' AND ward IN ('Bahati', 'Dundori', 'Kabatini', 'Kiamaina', 'Lanet/Umoja');
UPDATE kenya_wards SET constituency = 'Gilgil' WHERE county = 'Nakuru' AND ward IN ('Elementaita', 'Gilgil', 'Malewa West', 'Mbaruk/Eburu', 'Murindati');
UPDATE kenya_wards SET constituency = 'Kuresoi North' WHERE county = 'Nakuru' AND ward IN ('Kamara', 'Kiptororo', 'Nyota', 'Sirikwa');
UPDATE kenya_wards SET constituency = 'Kuresoi South' WHERE county = 'Nakuru' AND ward IN ('Amalo', 'Keringet', 'Kiptagich', 'Tinet');
UPDATE kenya_wards SET constituency = 'Molo' WHERE county = 'Nakuru' AND ward IN ('Elburgon', 'Mariashoni', 'Molo', 'Turi');
UPDATE kenya_wards SET constituency = 'Naivasha' WHERE county = 'Nakuru' AND ward IN ('Hells Gate', 'Lakeview', 'Maai-Mahiu', 'Maiella', 'Naivasha East', 'Olkaria', 'Viwandani');
UPDATE kenya_wards SET constituency = 'Nakuru Town East' WHERE county = 'Nakuru' AND ward IN ('Biashara', 'Flamingo', 'Kivumbini', 'Menengai', 'Nakuru East');
UPDATE kenya_wards SET constituency = 'Nakuru Town West' WHERE county = 'Nakuru' AND ward IN ('Barut', 'Kapkures', 'Kaptembwo', 'London', 'Rhoda', 'Shaabab');
UPDATE kenya_wards SET constituency = 'Njoro' WHERE county = 'Nakuru' AND ward IN ('Kihingo', 'Lare', 'Mauche', 'Maunarok', 'Nessuit', 'Njoro');
UPDATE kenya_wards SET constituency = 'Rongai' WHERE county = 'Nakuru' AND ward IN ('Menengai West', 'Mosop', 'Soin', 'Solai', 'Visoi');
UPDATE kenya_wards SET constituency = 'Subukia' WHERE county = 'Nakuru' AND ward IN ('Kabazi', 'Subukia', 'Waseges');
UPDATE kenya_wards SET constituency = 'Aldai' WHERE county = 'Nandi' AND ward IN ('Kabwareng', 'Kaptumo-Kaboi', 'Kemeloi-Maraba', 'Kobujoi', 'Koyo-Ndurio', 'Terik');
UPDATE kenya_wards SET constituency = 'Chesumei' WHERE county = 'Nandi' AND ward IN ('Chemundu/Kapng''Etuny', 'Kaptel/Kamoiywo', 'Kiptuya', 'Kosirai', 'Lelmokwo/Ngechek');
UPDATE kenya_wards SET constituency = 'Emgwen' WHERE county = 'Nandi' AND ward IN ('Chepkumia', 'Kapkangani', 'Kapsabet', 'Kilibwoni');
UPDATE kenya_wards SET constituency = 'Mosop' WHERE county = 'Nandi' AND ward IN ('Chepterwai', 'Kabisaga', 'Kabiyet', 'Kipkaren', 'Kurgung/Surungai', 'Ndalat', 'Sangalo/Kebulonik');
UPDATE kenya_wards SET constituency = 'Nandi Hills' WHERE county = 'Nandi' AND ward IN ('Chepkunyuk', 'Kapchorua', 'Nandi Hills', 'Ol''Lessos');
UPDATE kenya_wards SET constituency = 'Tinderet' WHERE county = 'Nandi' AND ward IN ('Chemelil/Chemase', 'Kapsimotwo', 'Songhor/Soba', 'Tindiret');
UPDATE kenya_wards SET constituency = 'Emurua Dikirr' WHERE county = 'Narok' AND ward IN ('Ilkerin', 'Kapsasian', 'Mogondo', 'Ololmasani');
UPDATE kenya_wards SET constituency = 'Kilgoris' WHERE county = 'Narok' AND ward IN ('Angata Barikoi', 'Keyian', 'Kilgoris Central', 'Kimintet', 'Lolgorian', 'Shankoe');
UPDATE kenya_wards SET constituency = 'Narok East' WHERE county = 'Narok' AND ward IN ('Ildamat', 'Keekonyokie', 'Mosiro', 'Suswa');
UPDATE kenya_wards SET constituency = 'Narok North' WHERE county = 'Narok' AND ward IN ('Melili', 'Narok Town', 'Nkareta', 'Olokurto', 'Olorropil', 'Olpusimoru');
UPDATE kenya_wards SET constituency = 'Narok South' WHERE county = 'Narok' AND ward IN ('Loita', 'Majimoto/Naroosura', 'Melelo', 'Ololulung''A', 'Sagamian', 'Sogoo');
UPDATE kenya_wards SET constituency = 'Narok West' WHERE county = 'Narok' AND ward IN ('Ilmotiok', 'Mara', 'Naikarra', 'Siana');
UPDATE kenya_wards SET constituency = 'Borabu' WHERE county = 'Nyamira' AND ward IN ('Esise', 'Kiabonyoru', 'Mekenene', 'Nyansiongo');
UPDATE kenya_wards SET constituency = 'Kitutu Masaba' WHERE county = 'Nyamira' AND ward IN ('Gachuba', 'Gesima', 'Kemera', 'Magombo', 'Manga', 'Rigoma');
UPDATE kenya_wards SET constituency = 'North Mugirango' WHERE county = 'Nyamira' AND ward IN ('Bokeira', 'Bomwagamo', 'Ekerenyo', 'Itibo', 'Magwagwa');
UPDATE kenya_wards SET constituency = 'West Mugirango' WHERE county = 'Nyamira' AND ward IN ('Bogichora', 'Bonyamatuta', 'Bosamaro', 'Nyamaiya', 'Township');
UPDATE kenya_wards SET constituency = 'Kinangop' WHERE county = 'Nyandarua' AND ward IN ('Engineer', 'Gathara', 'Githabai', 'Magumu', 'Murungaru', 'Njabini\Kiburu', 'North Kinangop', 'Nyakio');
UPDATE kenya_wards SET constituency = 'Kipipiri' WHERE county = 'Nyandarua' AND ward IN ('Geta', 'Githioro', 'Kipipiri', 'Wanjohi');
UPDATE kenya_wards SET constituency = 'Ndaragwa' WHERE county = 'Nyandarua' AND ward IN ('Central', 'Kiriita', 'Leshau Pondo', 'Shamata');
UPDATE kenya_wards SET constituency = 'Ol Jorok' WHERE county = 'Nyandarua' AND ward IN ('Charagita', 'Gathanji', 'Gatimu', 'Weru');
UPDATE kenya_wards SET constituency = 'Ol Kalou' WHERE county = 'Nyandarua' AND ward IN ('Kaimbaga', 'Kanjuiri Ridge', 'Karau', 'Mirangine', 'Rurii');
UPDATE kenya_wards SET constituency = 'Kieni' WHERE county = 'Nyeri' AND ward IN ('Gakawa', 'Gatarakwa', 'Kabaru', 'Mugunda', 'Mweiga', 'Mwiyogo/Endarasha', 'Naromoru Kiamathaga', 'Thegu River');
UPDATE kenya_wards SET constituency = 'Mathira' WHERE county = 'Nyeri' AND ward IN ('Iriaini', 'Karatina Town', 'Kirimukuyu', 'Konyu', 'Magutu', 'Ruguru');
UPDATE kenya_wards SET constituency = 'Mukurweini' WHERE county = 'Nyeri' AND ward IN ('Gikondi', 'Mukurwe-Ini Central', 'Mukurwe-Ini West', 'Rugi');
UPDATE kenya_wards SET constituency = 'Nyeri Town' WHERE county = 'Nyeri' AND ward IN ('Gatitu/Muruguru', 'Kamakwa/Mukaro', 'Kiganjo/Mathari', 'Ruring''U', 'Rware');
UPDATE kenya_wards SET constituency = 'Othaya' WHERE county = 'Nyeri' AND ward IN ('Chinga', 'Iria-Ini', 'Karima', 'Mahiga');
UPDATE kenya_wards SET constituency = 'Tetu' WHERE county = 'Nyeri' AND ward IN ('Aguthi/Gaaki', 'Dedan Kimanthi', 'Wamagana');
UPDATE kenya_wards SET constituency = 'Samburu East' WHERE county = 'Samburu' AND ward IN ('Wamba East', 'Wamba North', 'Wamba West', 'Waso');
UPDATE kenya_wards SET constituency = 'Samburu North' WHERE county = 'Samburu' AND ward IN ('Angata Nanyokie', 'Baawa', 'El-Barta', 'Nachola', 'Ndoto', 'Nyiro');
UPDATE kenya_wards SET constituency = 'Samburu West' WHERE county = 'Samburu' AND ward IN ('Lodokejek', 'Loosuk', 'Maralal', 'Poro', 'Suguta Marmar');
UPDATE kenya_wards SET constituency = 'Alego Usonga' WHERE county = 'Siaya' AND ward IN ('Central Alego', 'North Alego', 'Siaya Township', 'South East Alego', 'Usonga', 'West Alego');
UPDATE kenya_wards SET constituency = 'Bondo' WHERE county = 'Siaya' AND ward IN ('Central Sakwa', 'North Sakwa', 'South Sakwa', 'West Sakwa', 'West Yimbo', 'Yimbo East');
UPDATE kenya_wards SET constituency = 'Gem' WHERE county = 'Siaya' AND ward IN ('Central Gem', 'East Gem', 'North Gem', 'South Gem', 'West Gem', 'Yala Township');
UPDATE kenya_wards SET constituency = 'Rarieda' WHERE county = 'Siaya' AND ward IN ('East Asembo', 'North Uyoma', 'South Uyoma', 'West Asembo', 'West Uyoma');
UPDATE kenya_wards SET constituency = 'Ugenya' WHERE county = 'Siaya' AND ward IN ('East Ugenya', 'North Ugenya', 'Ukwala', 'West Ugenya');
UPDATE kenya_wards SET constituency = 'Ugunja' WHERE county = 'Siaya' AND ward IN ('Sidindi', 'Sigomere', 'Ugunja');
UPDATE kenya_wards SET constituency = 'Mwatate' WHERE county = 'Taita Taveta' AND ward IN ('Bura', 'Chawia', 'Mwatate', 'Rong''E', 'Wusi/Kishamba');
UPDATE kenya_wards SET constituency = 'Taveta' WHERE county = 'Taita Taveta' AND ward IN ('Bomeni', 'Chala', 'Mahoo', 'Mata', 'Mboghoni');
UPDATE kenya_wards SET constituency = 'Voi' WHERE county = 'Taita Taveta' AND ward IN ('Kaloleni', 'Kasigau', 'Marungu', 'Mbololo', 'Ngolia', 'Sagalla');
UPDATE kenya_wards SET constituency = 'Wundanyi' WHERE county = 'Taita Taveta' AND ward IN ('Mwanda/Mgange', 'Werugha', 'Wumingu/Kishushe', 'Wundanyi/Mbale');
UPDATE kenya_wards SET constituency = 'Bura' WHERE county = 'Tana River' AND ward IN ('Bangale', 'Bura', 'Chewele', 'Madogo', 'Sala');
UPDATE kenya_wards SET constituency = 'Galole' WHERE county = 'Tana River' AND ward IN ('Chewani', 'Kinakomba', 'Mikinduni', 'Wayu');
UPDATE kenya_wards SET constituency = 'Garsen' WHERE county = 'Tana River' AND ward IN ('Garsen Central', 'Garsen North', 'Garsen South', 'Garsen West', 'Kipini East', 'Kipini West');
UPDATE kenya_wards SET constituency = 'Chuka/Igambang''Om' WHERE county = 'Tharaka-Nithi' AND ward IN ('Igambang''Ombe', 'Karingani', 'Magumoni', 'Mariani', 'Mugwe');
UPDATE kenya_wards SET constituency = 'Maara' WHERE county = 'Tharaka-Nithi' AND ward IN ('Chogoria', 'Ganga', 'Mitheru', 'Muthambi', 'Mwimbi');
UPDATE kenya_wards SET constituency = 'Tharaka' WHERE county = 'Tharaka-Nithi' AND ward IN ('Chiakariga', 'Gatunga', 'Marimanti', 'Mukothima', 'Nkondi');
UPDATE kenya_wards SET constituency = 'Cherangany' WHERE county = 'Trans Nzoia' AND ward IN ('Chepsiro/Kiptoror', 'Cherangany/Suwerwa', 'Kaplamai', 'Makutano', 'Motosiet', 'Sinyerere', 'Sitatunga');
UPDATE kenya_wards SET constituency = 'Endebess' WHERE county = 'Trans Nzoia' AND ward IN ('Chepchoina', 'Endebess', 'Matumbei');
UPDATE kenya_wards SET constituency = 'Kiminini' WHERE county = 'Trans Nzoia' AND ward IN ('Hospital', 'Kiminini', 'Nabiswa', 'Sikhendu', 'Sirende', 'Waitaluk');
UPDATE kenya_wards SET constituency = 'Kwanza' WHERE county = 'Trans Nzoia' AND ward IN ('Bidii', 'Kapomboi', 'Keiyo', 'Kwanza');
UPDATE kenya_wards SET constituency = 'Saboti' WHERE county = 'Trans Nzoia' AND ward IN ('Kinyoro', 'Machewa', 'Matisi', 'Saboti', 'Tuwani');
UPDATE kenya_wards SET constituency = 'Loima' WHERE county = 'Turkana' AND ward IN ('Kotaruk/Lobei', 'Loima', 'Lokiriama/Lorengippi', 'Turkwel');
UPDATE kenya_wards SET constituency = 'Turkana Central' WHERE county = 'Turkana' AND ward IN ('Kalokol', 'Kanamkemer', 'Kang''Atotha', 'Kerio Delta', 'Lodwar Township');
UPDATE kenya_wards SET constituency = 'Turkana East' WHERE county = 'Turkana' AND ward IN ('Kapedo/Napeitom', 'Katilia', 'Lokori/Kochodin');
UPDATE kenya_wards SET constituency = 'Turkana North' WHERE county = 'Turkana' AND ward IN ('Kaaleng/Kaikor', 'Kaeris', 'Kibish', 'Lake Zone', 'Lapur', 'Nakalale');
UPDATE kenya_wards SET constituency = 'Turkana South' WHERE county = 'Turkana' AND ward IN ('Kalapata', 'Kaputir', 'Katilu', 'Lobokat', 'Lokichar');
UPDATE kenya_wards SET constituency = 'Turkana West' WHERE county = 'Turkana' AND ward IN ('Kakuma', 'Kalobeyei', 'Letea', 'Lokichoggio', 'Lopur', 'Nanaam', 'Songot');
UPDATE kenya_wards SET constituency = 'Ainabkoi' WHERE county = 'Uasin Gishu' AND ward IN ('Ainabkoi/Olare', 'Kapsoya', 'Kaptagat');
UPDATE kenya_wards SET constituency = 'Kapseret' WHERE county = 'Uasin Gishu' AND ward IN ('Kipkenyo', 'Langas', 'Megun', 'Ngeria', 'Simat/Kapseret');
UPDATE kenya_wards SET constituency = 'Kesses' WHERE county = 'Uasin Gishu' AND ward IN ('Cheptiret/Kipchamo', 'Racecourse', 'Tarakwa', 'Tulwet/Chuiyat');
UPDATE kenya_wards SET constituency = 'Moiben' WHERE county = 'Uasin Gishu' AND ward IN ('Karuna/Meibeki', 'Kimumu', 'Moiben', 'Sergoit', 'Tembelio');
UPDATE kenya_wards SET constituency = 'Soy' WHERE county = 'Uasin Gishu' AND ward IN ('Kapkures', 'Kipsomba', 'Kuinet/Kapsuswa', 'Moi''S Bridge', 'Segero/Barsombe', 'Soy', 'Ziwa');
UPDATE kenya_wards SET constituency = 'Turbo' WHERE county = 'Uasin Gishu' AND ward IN ('Huruma', 'Kamagut', 'Kapsaos', 'Kiplombe', 'Ngenyilel', 'Tapsagoi');
UPDATE kenya_wards SET constituency = 'Emuhaya' WHERE county = 'Vihiga' AND ward IN ('Central Bunyore', 'North East Bunyore', 'West Bunyore');
UPDATE kenya_wards SET constituency = 'Hamisi' WHERE county = 'Vihiga' AND ward IN ('Banja', 'Gisambai', 'Jepkoyai', 'Muhudu', 'Shamakhokho', 'Shiru', 'Tambua');
UPDATE kenya_wards SET constituency = 'Luanda' WHERE county = 'Vihiga' AND ward IN ('Emabungo', 'Luanda South', 'Luanda Township', 'Mwibona', 'Wemilabi');
UPDATE kenya_wards SET constituency = 'Sabatia' WHERE county = 'Vihiga' AND ward IN ('Busali', 'Chavakali', 'Lyaduywa/Izava', 'North Maragoli', 'West Sabatia', 'Wodanga');
UPDATE kenya_wards SET constituency = 'Vihiga' WHERE county = 'Vihiga' AND ward IN ('Central Maragoli', 'Lugaga-Wamuluma', 'Mungoma', 'South Maragoli');
UPDATE kenya_wards SET constituency = 'Eldas' WHERE county = 'Wajir' AND ward IN ('Della', 'Eldas', 'Elnur/Tula Tula', 'Lakoley South/Basir');
UPDATE kenya_wards SET constituency = 'Tarbaj' WHERE county = 'Wajir' AND ward IN ('Elben', 'Sarman', 'Tarbaj', 'Wargadud');
UPDATE kenya_wards SET constituency = 'Wajir East' WHERE county = 'Wajir' AND ward IN ('Barwago', 'Khorof/Harar', 'Township', 'Wagberi');
UPDATE kenya_wards SET constituency = 'Wajir North' WHERE county = 'Wajir' AND ward IN ('Batalu', 'Bute', 'Danaba', 'Godoma', 'Gurar', 'Korondile', 'Malkagufu');
UPDATE kenya_wards SET constituency = 'Wajir South' WHERE county = 'Wajir' AND ward IN ('Benane', 'Burder', 'Dadaja Bulla', 'Diif', 'Habasswein', 'Ibrahim Ure', 'Lagboghol South');
UPDATE kenya_wards SET constituency = 'Wajir West' WHERE county = 'Wajir' AND ward IN ('Ademasajide', 'Arbajahan', 'Hadado/Athibohol', 'Wagalla/Ganyure');
UPDATE kenya_wards SET constituency = 'Kacheliba' WHERE county = 'West Pokot' AND ward IN ('Alale', 'Kapckok', 'Kasei', 'Kiwawa', 'Kodich', 'Suam');
UPDATE kenya_wards SET constituency = 'Kapenguria' WHERE county = 'West Pokot' AND ward IN ('Endugh', 'Kapenguria', 'Mnagei', 'Riwo', 'Siyoi', 'Sook');
UPDATE kenya_wards SET constituency = 'Pokot South' WHERE county = 'West Pokot' AND ward IN ('Batei', 'Chepareria', 'Lelan', 'Tapach');
UPDATE kenya_wards SET constituency = 'Sigor' WHERE county = 'West Pokot' AND ward IN ('Lomut', 'Masool', 'Sekerr', 'Weiwei');
